Nesting locators and adding mouse hover actions
manuelam20/protractor-workshop-2018 pull request #13
Opened 2019-02-25 21:44 UTC by manuelam20

2019-02-25 23:13 UTC, jhenaoz requested changes

2019-02-25 23:13 UTC, jhenaoz commented on functions.js
> +// named function
remove this file

2019-02-25 23:13 UTC, jhenaoz commented on src/page/product-list.page.ts
> +  /*private findByProduct (productName : string) : ElementFinder {
remove this comment

2019-02-25 23:13 UTC, jhenaoz commented on test/busy-tshirt.spec.ts
> +      //  await productListPage.addTshirtToCart();
why this comment?

2019-02-26 14:40 UTC, manuelam20 commented on functions.js
> +// named function
file deleted

2019-02-26 14:40 UTC, manuelam20 commented on src/page/product-list.page.ts
> +  /*private findByProduct (productName : string) : ElementFinder {
comment deleted

2019-02-26 14:40 UTC, manuelam20 commented on test/busy-tshirt.spec.ts
> +      //  await productListPage.addTshirtToCart();
comment deleted

2019-02-26 15:06 UTC, jhenaoz approved these changes

2019-02-26 15:07 UTC, merged